(ns cryptic.vocabulary)

(def badjectives
  ["bad" "invalid" "illegal" "improper" "missing" "incorrect" "insufficient"
   "ambiguous" "malformed" "deprecated"])

(def weirdjectives
  ["ambitious" "operatic" "cryptic" "arcane" "archaic" "deliberate" "malicious"
   "aggressive" "ambient" "mysterious" "abundant" "incessant" "weird" "strange"
   "falsifiable" "impetuous" "skeptical" "forgettable" "laborious"
   "performative" "impeccable" "hasty" "pneumatic" "arable" "incandescent"
   "illegible" "aromatic" "flammable" "unfriendly" "omniscient" "benevolent"
   "suboptimal" "unrecoverable" "moribund" "gelatinous" "ecstatic"
   "indivisible" "implausible" "vacillating" "abhorrent" "abstract"
   "productive" "intangible" "factual" "irrelevant" "monochromatic"
   "undecidable" "entertaining" "fatuous" "gratuitous" "ingenuous"
   "superfluous" "ironic" "ambivalent" "philosophical" "majestic" "grandiose"
   "inarticulate" "immutable" "indirect" "monadic" "variadic" "inevitable"
   "colossal" "mellifluous" "recondite" "abstruse" "recalcitrant" "obstinate"
   "perverse" "defiant" "difficult" "wayward" "misleading" "inferior"
   "laborious" "stereotypical" "obscure" "inscrutable" "excruciating"
   "phosphorescent" "unfinished" "unbalanced" "impartial" "unqualified"
   "derivative" "unoriginal" "particulate" "precarious" "unsubtle"
   "androgynous" "insidious" "insipid" "infallible" "optional" "impossible"
   "innumerable" "numberless" "suggestive" "autosomal" "dominant" "somnolent"
   "ambulatory" "fastidious" "persnickety" "inexplicable" "obsolete" "ancient"
   "outdated" "deviant" "immodest" "foreign" "sturdy" "impressive" "facile"
   "significant" "recursive" "patriarchal" "violent" "merciful" "lewd" "rude"
   "reclusive" "innocuous" "staid" "vituperative" "abrasive" "disheveled"
   "incoherent" "sinister" "ferrous" "indicative" "nightmarish" "dismal"
   "arrogant" "sorcerous" "indigenous" "native" "mere" "domestic" "excessive"
   "flagrant" "crumbling" "faltering" "fell" "ghastly" "veiled" "virtual"
   "joyous" "delirious" "paranoid" "mutual" "benign" "malevolent" "drab"
   "mundane" "considerable" "credulous" "sacrificial" "specious" "savage"
   "delectable" "ashen" "inappropriate" "sparse" "spare" "secondhand"
   "adjoining" "dubious" "absurd" "sickening" "prodigious" "primitive"
   "schismatic" "fractious"])

(def nouns
  ["accusation" "admixture" "assumption" "argument" "axiom" "batch"
   "constraint" "corpus" "gender" "fugitive" "party" "entity" "word" "rule"
   "number" "parameter" "operation" "suggestion" "advice" "insertion"
   "deletion" "removal" "access" "symbol" "variable" "formula" "request"
   "command" "action" "permission" "type" "name" "reference" "object" "plea"
   "article" "inquiry" "query" "quandary" "question" "file" "path" "error"
   "exception" "warning" "violation" "activity" "task" "performance" "branch"
   "case" "switch" "function" "default" "handler" "clause" "handle" "queue"
   "collection" "iterator" "item" "data" "transaction" "transformation"
   "meme" "deity" "invocation" "matrix" "array" "set" "map" "hash" "test"
   "condition" "consequent" "alternative" "scene" "graph" "plot" "wizard"
   "anomaly" "prophecy" "operator" "functor" "application" "thread" "process"
   "overflow" "jail" "escape" "recursion" "depth" "vector" "window"
   "component" "operand" "machinery" "pipe" "widget" "spell" "arrow"
   "database" "package" "statement" "expression" "justification" "parse"
   "tree" "parser" "analyzer" "loader" "linker" "library" "module" "routine"
   "class" "hierarchy" "attribute" "method" "callback" "monad" "architecture"
   "target" "assembler" "language" "line" "column" "row" "scope" "closure"
   "binding" "abstraction" "entry" "token" "trace" "hack" "dependency"
   "resolution" "keyword" "stopword" "atom" "procedure" "directory" "mode"
   "user" "flag" "box" "property" "phrase" "traceback" "stack" "heap"
   "state" "arity" "leaf" "signal" "password" "character" "factory" "filter"
   "lambda" "recipe" "transducer" "system" "interface" "implementation"
   "logic" "form" "syntax" "icon" "effigy" "comment" "document" "namespace"
   "primitive" "lexer" "reader" "loop" "event" "predicate" "promise" "job"
   "rune" "monolith" "judge" "spline" "status" "relationship" "trust" "key"
   "index" "portal" "gate" "commit" "constructor" "destructor" "zine" "missive"
   "briefing" "journal" "observer" "panoply" "panopticon" "pension" "witness"
   "macro" "suspicion" "hypotenuse" "option" "world" "pointer" "counter" "lock"
   "gesture" "meaning" "content" "shader" "fragment" "subordinate" "selection"
   "election" "booth" "limb" "whim" "cognate" "injury" "bridge" "penalty"
   "blueprint" "flange" "body" "flesh" "fringe" "genius" "kind" "urge"
   "paradigm" "gem" "snake" "pod" "role" "semantics" "destruction" "habit"
   "passion" "economy" "bottom" "model" "editor" "injection" "poem" "song"
   "humanity" "mandible" "indictment" "evidence" "fugue" "parsimony" "tangent"
   "policy" "strategy" "layer" "tool" "ruin" "crucible" "rubble" "furnace"
   "bell" "thumb" "finger" "joint" "hinge" "head" "tail" "regime" "wing"
   "crate" "container" "ghost" "spirit" "soul" "cancer" "delirium" "period"
   "calendar" "agenda" "conspiracy" "calamity" "ritual" "society" "law"
   "jurisdiction" "propriety" "dictionary" "consideration" "clasp" "species"
   "field" "lever" "medium" "dirge" "deluge" "urn" "pile" "individuality"
   "identity" "drug" "pool" "knowledge" "basis" "conviction" "mind"
   "intelligence" "doubt" "nausea" "nomenclature" "traversal" "circumstances"
   "surroundings" "environment" "strut" "guilt" "family" "malfeasance" "dome"
   "sphere" "orb" "fact" "schism" "comeuppance" "zodiac"])

(def verbs
  ["elongate" "instantiate" "create" "wrap" "investigate" "mangle" "munge"
   "disentangle" "splice" "cause" "invent" "devise" "derive" "signify"
   "attempt" "handle" "hack" "elucidate" "falsify" "negate" "perform" "operate"
   "articulate" "remove" "insert" "delete" "erase" "swap" "clone" "jump to"
   "slice" "inspect" "examine" "calcify" "separate" "disambiguate" "call"
   "invoke" "reincarnate" "update" "dissociate" "associate" "surround"
   "consume" "parse" "lex" "tokenize" "analyze" "compile" "link" "send" "pass"
   "recur to" "imply" "infer" "reify" "realize" "specify" "conform to"
   "comply with" "speculate on" "project" "protect" "escape" "imprison" "stop"
   "quit" "prevent" "validate" "comprehend" "impregnate" "endure" "accept"
   "contend with" "ameliorate" "problematize" "criticize" "systematize"
   "enshrine" "elevate" "embrace" "discard" "renege on" "betray" "ignore"
   "question" "push" "extinguish" "revise" "envision" "memoize" "amortize"
   "write" "read" "receive" "enjoy" "redirect" "tolerate" "commit" "render"
   "imprecate" "utter" "disestablish" "excommunicate" "understand" "present"
   "force" "forecast" "evoke" "downcast" "foretell" "foresee" "forfeit"
   "forfend" "grok" "eviscerate" "elide" "emit" "omit" "transcend" "reduce"
   "conduct" "eject" "ensure" "verify" "demarcate" "perceive" "conceive"
   "dismiss" "downplay" "exceed" "enthrall" "stigmatize" "intercept"
   "establish" "clarify" "revive" "relinquish" "guess" "eliminate" "unwrap"
   "expunge" "describe" "enumerate" "lock" "encase" "encapsulate" "enclose"
   "count" "suggest" "explain" "convince" "persuade" "preempt" "forestall"
   "acquire" "appropriate" "abscond with" "elope with" "grasp" "seize" "occupy"
   "inhabit" "commandeer" "arrogate" "usurp" "reserve" "evince" "indicate"
   "manifest" "exhibit" "display" "translate" "bind" "subvert" "find" "locate"
   "select" "reject" "detect" "inject" "elect" "poll" "afflict" "inflict"
   "design" "prepare" "partition" "subjugate" "improve" "suppress" "subdue"
   "furnish" "announce" "denounce" "deny" "become" "evaluate" "insinuate"
   "object to" "excise" "resist" "preserve" "maintain" "virtualize"
   "consent to" "engage" "consider" "sacrifice" "destroy" "undo" "enunciate"
   "pronounce" "assert" "affirm" "declare" "pardon" "suspend" "excuse"
   "renounce" "amplify" "traverse" "bypass" "ensnare" "encircle" "tabulate"
   "support" "prop up" "possess" "rehabilitate" "redeem" "facilitate"])
